# Задача о погоне
Задание №1: Вывод дифференциальных уравнений для случая n-кратного превышения скорости
**Цель:** Провести аналогичные рассуждения и вывод дифференциальных уравнений,
если скорость катера больше скорости лодки в n раз.

## Инициализация проекта и загрузка пакетов

```{julia}
using Pkg
Pkg.activate("C:/Users/Александра/work/study/2026-1/2026-1==study--mathmod/2026-1--study--mathmod/labs/lab02/project")
using DrWatson
@quickactivate "project"
using DifferentialEquations
using Plots
using JLD2

script_name = "zadacha_o_pogone01"
mkpath(plotsdir(script_name))
mkpath(datadir(script_name))
```

## Параметры варианта 35
Начальное расстояние между катером и лодкой: k = 18 км
Отношение скоростей: n = 4.9 (катер в 4.9 раз быстрее лодки)
Угол движения лодки: fi = 3*pi/4

```{julia}
k = 18.0
n = 4.9
fi = 3*pi/4

println("=== Вариант 35 ===")
println("k = $k км, n = $n, fi = $(round(fi*180/pi, digits=1))°")
```

## Вывод дифференциального уравнения

По условию задачи скорость катера V в n раз больше скорости лодки v:
V = n * v

1. Найдем расстояние x, на котором катер должен выйти на одну радиальную
   координату с лодкой.

   Случай 1 (катер между полюсом и лодкой):
   За время t лодка пройдет расстояние x, катер пройдет расстояние k - x.
   Так как время одно и то же:
   x / v = (k - x) / (n * v)
   n * x = k - x
   x * (n + 1) = k
   x1 = k / (n + 1)

   Случай 2 (полюс между катером и лодкой):
   За время t лодка пройдет расстояние x, катер пройдет расстояние x + k.
   x / v = (x + k) / (n * v)
   n * x = x + k
   x * (n - 1) = k
   x2 = k / (n - 1)

## Определение начальных условий
Случай 1: катер между полюсом и лодкой

```{julia}
r0_1 = k / (n + 1)
```

Случай 2: полюс между катером и лодкой

```{julia}
r0_2 = k / (n - 1)
```

Начальные условия

```{julia}
println("\nНачальные условия:")
println("Случай 1: r0_1 = k/(n+1) = $k/$(n+1) = $(round(r0_1, digits=4)) км")
println("Случай 2: r0_2 = k/(n-1) = $k/$(n-1) = $(round(r0_2, digits=4)) км")
```

## Вывод дифференциального уравнения движения катера

После того, как катер оказался на одном расстоянии от полюса с лодкой,
он должен двигаться вокруг полюса, удаляясь от него со скоростью лодки v.

Скорость катера V = n*v раскладываем на две составляющие:
- радиальная скорость: v_r = dr/dt (скорость удаления от полюса)
- тангенциальная скорость: v_t = r * dtheta/dt (линейная скорость вращения)

Чтобы катер удалялся от полюса с той же скоростью, что и лодка:
dr/dt = v

Тогда из прямоугольного треугольника скоростей:
V^2 = v_r^2 + v_t^2
(n*v)^2 = v^2 + v_t^2
v_t^2 = n^2 * v^2 - v^2 = v^2 * (n^2 - 1)
v_t = v * sqrt(n^2 - 1)

Так как v_t = r * dtheta/dt, получаем:
r * dtheta/dt = v * sqrt(n^2 - 1)
dtheta/dt = v * sqrt(n^2 - 1) / r

Разделим dr/dt на dtheta/dt:
dr/dtheta = (dr/dt) / (dtheta/dt) = v / (v * sqrt(n^2 - 1) / r)
dr/dtheta = r / sqrt(n^2 - 1)

Таким образом, дифференциальное уравнение траектории катера:
dr/dtheta = r / sqrt(n^2 - 1)

## Решение дифференциального уравнения
Функция правой части: dr/dtheta = r / sqrt(n^2 - 1)

```{julia}
function f(r, p, theta)
    return r / sqrt(n^2 - 1)
end
```

Случай 1: theta in [0, 2*pi]

```{julia}
tspan1 = (0.0, 2*pi)
prob1 = ODEProblem(f, r0_1, tspan1)
sol1 = solve(prob1, Tsit5(), saveat=0.01)
```

Случай 2: theta in [-pi, pi]

```{julia}
tspan2 = (-pi, pi)
prob2 = ODEProblem(f, r0_2, tspan2)
sol2 = solve(prob2, Tsit5(), saveat=0.01)
```

## Точки пересечения с траекторией лодки (theta = fi)

```{julia}
r_meet1 = sol1(fi)
r_meet2 = sol2(fi)

println("\nТочки пересечения с траекторией лодки:")
println("Случай 1: r1 = $(round(r_meet1, digits=4)) км")
println("Случай 2: r2 = $(round(r_meet2, digits=4)) км")
```

## Визуализация траекторий
Данные для траектории лодки (прямая линия под углом fi)

```{julia}
theta_boat = [fi, fi]
r_boat = [0, 25]

p1 = plot(sol1.t, sol1.u, proj=:polar, lims=(0, 22),
          title="Случай 1: катер между полюсом и лодкой",
          label="Катер", lw=2, color=:blue)
plot!(p1, theta_boat, r_boat, label="Лодка", linestyle=:dash, color=:red, lw=2)

p2 = plot(sol2.t, sol2.u, proj=:polar, lims=(0, 22),
          title="Случай 2: полюс между катером и лодкой",
          label="Катер", lw=2, color=:green)
plot!(p2, theta_boat, r_boat, label="Лодка", linestyle=:dash, color=:red, lw=2)

final_plot = plot(p1, p2, layout=(1, 2), size=(1200, 550))
```

Сохранение результатов

```{julia}
savefig(final_plot, plotsdir(script_name, "trajectories_var35.png"))

println("\nГрафики сохранены в папку plots/")
```

Сохранение данных

```{julia}
@save datadir(script_name, "results.jld2") sol1 sol2 r_meet1 r_meet2
```

